package com.dbdoc.common.model;

import com.dbdoc.common.model.base.BaseConfigure;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Configure extends BaseConfigure<Configure> {
	
}
