package com.dbdoc.common.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseConfigure<M extends BaseConfigure<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public Integer getId() {
		return get("id");
	}

	public void setName(String name) {
		set("name", name);
	}

	public String getName() {
		return get("name");
	}

	public void setIp(String ip) {
		set("ip", ip);
	}

	public String getIp() {
		return get("ip");
	}

	public void setPort(Integer port) {
		set("port", port);
	}

	public Integer getPort() {
		return get("port");
	}

	public void setUsername(String username) {
		set("username", username);
	}

	public String getUsername() {
		return get("username");
	}

	public void setPassword(String password) {
		set("password", password);
	}

	public String getPassword() {
		return get("password");
	}

	public void setDbtype(Integer dbtype) {
		set("dbtype", dbtype);
	}

	public Integer getDbtype() {
		return get("dbtype");
	}
	
	public void setSID(String SID) {
		set("SID", SID);
	}

	public String getSID() {
		return get("SID");
	}

}
